### PR TITLE
Add mediaID to example property

### PR DESCRIPTION
**Pull request by KevinBatdorf**
Without it, the example doesn't render.

### CODE REVIEW

**Comment by ryanwelcher** [comment]
Hi @KevinBatdorf and thanks for putting this together!

Can you add some steps to reproduce this? I was not able to see any errors in the block after building from `master` branch but perhaps I missed a step.

**Comment by KevinBatdorf** [comment]
I'll give it a try tonight maybe. This PR is from February so it may have resolved itself even. But looking briefly, the signature expects a mediaId of type number and in the example it's not supplied at all.

**Comment by ryanwelcher** [comment]
OK great!  The way this block is built, it doesn't require a mediaID to render the initial state of the block. In the example, there isn't one set so it will render the upload image box - setting it would require there is an attachment post type with that specific ID in the database.

Please do let me know if you run into errors and we'll get it sorted out!

**Comment by KevinBatdorf** [comment]
Just tested it out on the code i was playing around with back then and it works now without the ID there. it must have resolved itself with a dependency update with the live preview or something along those lines. 

Next time I'll add a video or something to make it easier to demo. It was likely overly obvious at the time so i didn't think about it.

**Pull request closed without merging**
