### PR TITLE
Fix fatal error (WordPress#59)

### PR DESCRIPTION
**Pull request by nicowolf**
Not sure if I completely understood the usage of wp_set_script_translations() but at least the fatal error is gone.

### CODE REVIEW

**Comment by swissspidy** [comment]
See https://make.wordpress.org/core/2018/11/09/new-javascript-i18n-support-in-wordpress/ for how that new function works.

**Comment by swissspidy** [comment]
Awesome, thanks for the change.

I wonder where we could document that there is an optional third parameter to `wp_set_script_translations()` that needs to be used depending on the use case.

**Comment by nicowolf** [comment]
Hmm. I wouldn’t go into too much detail, since I’d imagine the users of the gutenberg-example might be more interested into getting their first block up and running (without worrying too much about translations at this point). At least I was, since there hardly was anything to translate in my first blocks. So maybe a comment like this would suffice:

`May be extended to wp_set_script_translations( 'my-handle', 'my-domain', array( 'wp-i18n' ) ). For details see https://make.wordpress.org/core/2018/11/09/new-javascript-i18n-support-in-wordpress/`

What do you think?

**Comment by swissspidy** [comment]
The third parameter is a path to a translations folder, not an array of dependencies :-)

**Comment by nicowolf** [comment]
D’oh. I was still asleep, obviously – how about this?

**Comment by nicowolf** [comment]
Hm, I just noticed that getting rid of the whole inline script part caused new errors (JS this time) in all block.js but the stylesheet-example. For example in 01-basic/index.php, line 19 ...
`i18n.setLocaleData( window.gutenberg_examples_01.localeData, 'gutenberg-examples' );` causes »Uncaught TypeError: Cannot read property 'localeData' of undefined« since we removed line 56 ...
`'var gutenberg_examples_01 = { localeData: %s };',`.
... from index.php

Unfortunately I have zero experience in localization, so I’ve no idea if we need to re-establish the variable or get rid of the part loading it.

**Comment by swissspidy** [comment]
Sorry, can you add a link to where there is some inline JS being loaded? 🤔 There shouldn‘t be any.

**Comment by nicowolf** [comment]
Line 19 of [block.js](https://github.com/nicowolf/gutenberg-examples/blob/bugfix/01-basic/block.js) tries to load `'window.gutenberg_examples_01.localeData'`, which was defined (I think) in the wp_inline_script()-part we’ve just removed from bugfix [index.php](https://github.com/nicowolf/gutenberg-examples/blob/bugfix/01-basic/index.php).

It’s still included in the master [index.php](https://github.com/WordPress/gutenberg-examples/blob/master/01-basic/index.php), line 56.

**Comment by swissspidy** [comment]
Oh yeah that stuff is not needed anymore

**Comment by baezor** [comment]
@nicowolf You rock man. I was trying for first time Gutenberg and I couldn't running until I found this PR. Thanks!

**Comment by nicowolf** [comment]
@swissspidy Okay, I removed those lines. The JS error is gone.

@baezor Thanks mate. I’m glad it actually helped anyone 😜

**Pull request merged**
