### PR TITLE
Update the 01-basic-esnext block to use block.json

### PR DESCRIPTION
**Pull request by ryanwelcher**
The PR updates the existing block to use version 2 of the api and block.json

### CODE REVIEW

**Comment by ryanwelcher** [comment]
@gziolo @mkaz wondering if either one of you can help me track down the issues I am seeing with `lerna` running the linting command? Running the `lint:js` command in each block directory works but I run it from the root, I get the error you see in the checks ( missing prettier ).

**Comment by simonhammes** [comment]
@ryanwelcher The error might be related to this issue: https://github.com/WordPress/gutenberg/issues/21872

**Comment by mkaz** [comment]
Instead of commenting out the lint rule, could we add prettier as a dependency to this project? If I'm reading the linked ticket correctly, it might help. My concern is once linting gets commented out it will slowly drift.

**Comment by ryanwelcher** [comment]
> Instead of commenting out the lint rule, could we add prettier as a dependency to this project? If I'm reading the linked ticket correctly, it might help. My concern is once linting gets commented out it will slowly drift.

I tried doing that and while it fixed the error, it was then failing based on the some whitespace difference with prettier vs the eslint rules. I'm not advocating for no linting, but this issues is blocking being able to move PR's forward, so perhaps an alternate approach such as husky might be in order?

**Review by mkaz — APPROVED** [review]
I see the same prettier error when trying within the `01-basic-esnext` directory, but this happens before and with the patch so I think relatively unrelated.

The rest looks good builds properly, plugin works, block.json looks good :+1:

**Pull request merged**
